/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package g4s22p4rpr;

/**
 *
 * @author ABIGAILSOFIA
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /** Creates new form FrmPrincipal */
    public FrmPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dppanel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Isuma = new javax.swing.JMenuItem();
        IResta = new javax.swing.JMenuItem();
        IMultiplicasion = new javax.swing.JMenuItem();
        IDivision = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        IRaiz = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.layout.GroupLayout dppanelLayout = new org.jdesktop.layout.GroupLayout(dppanel);
        dppanel.setLayout(dppanelLayout);
        dppanelLayout.setHorizontalGroup(
            dppanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 574, Short.MAX_VALUE)
        );
        dppanelLayout.setVerticalGroup(
            dppanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 249, Short.MAX_VALUE)
        );

        jMenu1.setText("Operaciones");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        Isuma.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_CONTROL, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        Isuma.setText("Suma");
        Isuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsumaActionPerformed(evt);
            }
        });
        jMenu1.add(Isuma);

        IResta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_CONTROL, java.awt.event.InputEvent.ALT_DOWN_MASK));
        IResta.setText("Resta");
        IResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IRestaActionPerformed(evt);
            }
        });
        jMenu1.add(IResta);

        IMultiplicasion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_0, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        IMultiplicasion.setText("Multiplicasion");
        IMultiplicasion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMultiplicasionActionPerformed(evt);
            }
        });
        jMenu1.add(IMultiplicasion);

        IDivision.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        IDivision.setText("Division");
        IDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDivisionActionPerformed(evt);
            }
        });
        jMenu1.add(IDivision);
        jMenu1.add(jSeparator1);

        IRaiz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        IRaiz.setText("Raiz Cuadrada");
        jMenu1.add(IRaiz);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acerca de");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem6.setText("Desarrollador");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dppanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dppanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsumaActionPerformed
        // TODO add your handling code here:
        FrmSuma frmsuma = new FrmSuma();
        frmsuma.setVisible(true);
        dppanel.add(frmsuma);
    }//GEN-LAST:event_IsumaActionPerformed

    private void IRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IRestaActionPerformed
        // TODO add your handling code here:
        FrmResta frresta = new FrmResta();
        frmresta.setVisible(true);
        dppanel.add(frmresta);
    }//GEN-LAST:event_IRestaActionPerformed

    private void IMultiplicasionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMultiplicasionActionPerformed
        // TODO add your handling code here:
        FrmMultiplicasion frmmultiplicasion = new FrmMultiplicasion();
        frmmultiplicasion.setVisible(true);
        dppanel.add(frmmultiplicasion);
    }//GEN-LAST:event_IMultiplicasionActionPerformed

    private void IDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDivisionActionPerformed
        // TODO add your handling code here:
        FrmDivision frmdivision = new FrmDivision();
        frmdivision.setVisible(true);
        dppanel.add(frmdivision);
    }//GEN-LAST:event_IDivisionActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        FrmRaiz frmraiz = new FrmRaiz();
        frmraiz.setVisible(true);
        dppanel.add(frmraiz);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        FrmDesarrolla frmdesarrolla = new frmDesarrolla ();
        frmdesarrolla.setVisile(true);
        dppanel.add(frmdesarrolla);
    }//GEN-LAST:event_jMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem IDivision;
    private javax.swing.JMenuItem IMultiplicasion;
    private javax.swing.JMenuItem IRaiz;
    private javax.swing.JMenuItem IResta;
    private javax.swing.JMenuItem Isuma;
    private javax.swing.JDesktopPane dppanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
